---
# Create a selfsigned Issuer for the root CA certificate
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "cert-manager-webhook-opusdns.selfSignedIssuer" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "cert-manager-webhook-opusdns.labels" . | nindent 4 }}
spec:
  selfSigned: {}

---
# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "cert-manager-webhook-opusdns.rootCACertificate" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "cert-manager-webhook-opusdns.labels" . | nindent 4 }}
spec:
  secretName: {{ include "cert-manager-webhook-opusdns.rootCACertificate" . }}
  duration: 43800h0m0s # 5y
  issuerRef:
    name: {{ include "cert-manager-webhook-opusdns.selfSignedIssuer" . }}
  commonName: "ca.cert-manager-webhook-opusdns.cert-manager"
  isCA: true

---
# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "cert-manager-webhook-opusdns.rootCAIssuer" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "cert-manager-webhook-opusdns.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "cert-manager-webhook-opusdns.rootCACertificate" . }}

---
# Generate a serving certificate for the webhook
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "cert-manager-webhook-opusdns.servingCertificate" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "cert-manager-webhook-opusdns.labels" . | nindent 4 }}
spec:
  secretName: {{ include "cert-manager-webhook-opusdns.servingCertificate" . }}
  duration: 8760h0m0s # 1y
  issuerRef:
    name: {{ include "cert-manager-webhook-opusdns.rootCAIssuer" . }}
  dnsNames:
    - {{ include "cert-manager-webhook-opusdns.fullname" . }}
    - {{ include "cert-manager-webhook-opusdns.fullname" . }}.{{ .Release.Namespace }}
    - {{ include "cert-manager-webhook-opusdns.fullname" . }}.{{ .Release.Namespace }}.svc
